mount_point = "/Users/dimitar.dimitrov/spork/mnt/sporkfs-71"
data_dir = "/Users/dimitar.dimitrov/spork/data/storage-71"
redundancy = 2
all_peers = ["localhost:1771", "localhost:1770"]
this_peer = "localhost:1771"
