---
kind: pipeline
type: docker
name: default

platform:
  os: linux

steps:
- name: test
  image: donkorleone/spork-build:latest
  privileged: true
  commands:
  - make
  volumes:
    - name: fuse
      path: /dev/fuse

volumes:
- name: fuse
  host:
    path: /dev/fuse

trigger:
  event:
  - push

...
