---
kind: pipeline
name: default
platform:
  os: linux
  arсh: amd64
workspace:
  base: /go
  path: src/github.com/dimitarvdimitrov/spork

steps:
  - name: test
    image: golang:1.13
    commands:
      - make
---
kind: pipeline
name: deploy
platform:
  os: linux
  arсh: amd64
steps:
  - name: deploy
    image: jmccann/drone-terraform:6.1-0.12.8
    commands:
      - cd infrastructure
      - terraform init
      - TF_VAR_squid_version=$DRONE_COMMIT terraform apply -auto-approve
    environment:
      DIGITALOCEAN_TOKEN:
        from_secret: digitalocean_token
depends_on: [default]
trigger:
  branch: [master]
